### PR TITLE
Bump to Chisel 6, migrate to svsim

### PR DESCRIPTION
**Pull request by seldridge**
Bump the template to Chisel 6.  Drop the ChiselTest dependency and migrate to svsim.

The test is not as efficient as it could be right now. However, it works!

### CODE REVIEW

**Comment by schoeberl** [comment]
LGTM. At least we see now svsim in action. Still very low lever, but I think we can build on that.

**Comment by seldridge** [comment]
> LGTM. At least we see now svsim in action. Still very low lever, but I think we can build on that.

Yep! Please start seeing if this would work for you and your teaching. 

Note that this example be made much, much cleaner. I don't see why we couldn't add the equivalent of `enqueueSeq` and `dequeueSeq` at a minimum. This can also land directly in Chisel's svsim area so it works for any decoupled. Fork and join are more tedious, but I don't see why this couldn't be made to work.

**Comment by seldridge** [comment]
This works in CI with a manual Verilator install. The installation can be sped up by properly setting up `ccache` (which Verilator is configured to use by default). 🎊  It would also be worthwhile to see if upstream verilator would accept (or we implement) a GitHub action that just does the Verilator install reusably.

**Comment by schoeberl** [comment]
> > LGTM. At least we see now svsim in action. Still very low lever, but I think we can build on that.
> 
> Yep! Please start seeing if this would work for you and your teaching.
> 
> Note that this example can be made much, much cleaner. I don't see why we couldn't add the equivalent of `enqueueSeq` and `dequeueSeq` at a minimum. This can also land directly in Chisel's svsim area so it works for any decoupled. Fork and join are more tedious, but I don't see why this couldn't be made to work.

Yes, to fork and join. It needs to be a bit nicer/polished UI for use in teaching. I will start playing around with it soon ;-)
However, I still think we should provide an ChiselTest version based on svsim, with a compatible API. Of course, not using SFC. Just the interface.

**Review by jackkoenig — APPROVED** [review]

**Pull request merged**
